name: check
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - run: nix flake check
