name: publish
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - run: nix flake check
      - name: build container
        run: |
          nix build .#
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker load --input ./result
          tag=$(date +%s)
          docker image tag ghcr.io/jgero/synapse-keycloak-self-service ghcr.io/jgero/synapse-keycloak-self-service:${tag}
          docker push ghcr.io/jgero/synapse-keycloak-self-service:${tag}
